export interface KBChunk {
  id: string;
  topic: string;
  text: string;
  keywords: string[];
  link?: string;
}

export const profileKB: KBChunk[] = [
  {
    id: "kb-amazon-role",
    topic: "Current role at Amazon",
    text: "Siddartha is a Software Development Engineer at Amazon in Seattle, on the AWS Quick RAG team, where he has worked since October 2024. He builds high-throughput ingestion pipelines for Amazon Quick Suite, Q Business, and Kendra that process 10,000+ documents a day and power RAG and LLM experiences over enterprise data.",
    keywords: [
      "job",
      "work",
      "amazon",
      "current role",
      "current job",
      "employer",
      "aws quick rag",
      "quick suite",
      "q business",
      "kendra",
      "sde",
      "software development engineer",
      "seattle",
      "rag",
      "rag systems",
      "built rag",
      "rag pipelines",
      "rag experience",
      "team",
      "amazon team",
      "which team",
      "role at amazon",
      "work",
      "works at amazon",
      "where does he work",
      "where he works",
      "place of work",
      "company",
      "current employer",
      "currently work for",
      "llm",
      "seniority",
      "experience level",
    ],
    link: "/experience",
  },
  {
    id: "kb-amazon-impact",
    topic: "Amazon impact and engineering details",
    text: "At Amazon, Siddartha architected large-scale index re-ingestion workflows that eliminate manual operations and enable zero-downtime updates as ML models evolve. He worked with cross-functional product and science teams to standardize ingestion across 10+ enterprise document formats, and he streamlined index ingestion by integrating validation and safe rollout mechanisms into CI/CD workflows, delivering 60% faster deployments for ML teams.",
    keywords: [
      "amazon impact",
      "re-ingestion",
      "zero downtime",
      "ci/cd",
      "deployment",
      "60%",
      "enterprise formats",
      "validation",
      "safe rollout",
      "index",
      "ingestion pipeline",
      "architecture",
      "system architecture",
      "system design",
      "architected",
      "designed systems",
      "technical challenge",
      "biggest challenge",
      "challenging project",
      "high throughput",
      "big data",
      "streaming pipelines",
      "data pipelines",
      "achievements",
      "achieved at amazon",
      "accomplished",
      "accomplishments",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-role",
    topic: "Cloud Engineer role at People Tech Group",
    text: "Before Amazon, Siddartha was a Cloud Engineer at People Tech Group in Seattle from April 2024 to October 2024. He led customer demos for a GenAI-driven MLOps solution that converts natural-language prompts into validated Infrastructure-as-Code deployments, cutting release timelines by 35%.",
    keywords: [
      "people tech group",
      "cloud engineer",
      "previous job",
      "genai",
      "generative ai",
      "genai projects",
      "mlops",
      "natural language",
      "infrastructure as code",
      "iac",
      "35%",
      "release timelines",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-hca",
    topic: "HCA Healthcare document pipeline",
    text: "At People Tech Group, Siddartha built an AWS-based consent-forms processing pipeline for HCA Healthcare that used AI/ML to extract data from handwritten forms. This reduced manual data entry by more than 80% and shortened turnaround from days to minutes.",
    keywords: [
      "hca healthcare",
      "healthcare",
      "handwritten forms",
      "consent forms",
      "document pipeline",
      "80%",
      "manual entry",
      "ocr",
      "extraction",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-infra",
    topic: "Infrastructure optimization at People Tech Group",
    text: "Siddartha also implemented automated scaling policies derived from cloud-usage analysis at People Tech Group, cutting infrastructure costs by 15%. He designed traffic-splitting algorithms that reduced microservice latency by 40ms for real-time AI inference workloads.",
    keywords: [
      "scaling policies",
      "cost reduction",
      "15%",
      "traffic splitting",
      "latency",
      "40ms",
      "microservices",
      "infrastructure",
      "real-time inference",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-njit",
    topic: "MS in Cyber Security & Privacy at NJIT",
    text: "Siddartha holds a Master of Science in Cyber Security & Privacy from the New Jersey Institute of Technology (NJIT). This graduate degree complements his software engineering background with a strong foundation in security and privacy principles applied to cloud and AI systems.",
    keywords: [
      "education",
      "njit",
      "masters",
      "ms",
      "cyber security",
      "privacy",
      "degree",
      "new jersey institute of technology",
      "school",
      "went to school",
      "college",
      "university",
      "studied",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-klu",
    topic: "B.Tech at KL University",
    text: "Siddartha earned his Bachelor of Technology in Computer Science & Engineering from the Koneru Lakshmaiah Education Foundation (KL University), which laid the foundation for his career in software development and cloud engineering.",
    keywords: [
      "education",
      "kl university",
      "koneru lakshmaiah",
      "btech",
      "b.tech",
      "bachelor",
      "bachelors degree",
      "undergrad",
      "computer science",
      "undergraduate degree",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-iwu",
    topic: "Ongoing graduate study at Indiana Wesleyan University",
    text: "Siddartha is currently deepening his AI/ML expertise through graduate studies in AI & Machine Learning at Indiana Wesleyan University (IWU), in progress alongside his full-time work at Amazon.",
    keywords: [
      "education",
      "iwu",
      "indiana wesleyan university",
      "ai/ml program",
      "graduate studies",
      "in progress",
      "machine learning degree",
      "studying",
      "currently studying",
      "study",
    ],
    link: "/experience",
  },
  {
    id: "kb-communication",
    topic: "Communication & speaking",
    text: "Siddartha is a strong communicator and comfortable speaker: he led weekly knowledge-sharing sessions at Amazon, mentored 6 engineers on GenAI and DevOps practices, and led customer-facing demos at People Tech Group that turned technical GenAI concepts into wins for non-technical stakeholders. Explaining complex AI systems clearly — to executives, customers, or new engineers — is one of his core strengths.",
    keywords: [
      "speaking",
      "speak",
      "public speaking",
      "communication",
      "communicator",
      "presentation",
      "presenting",
      "demos",
      "soft skills",
      "verbal",
      "articulate",
      "explain",
      "stakeholders",
      "good in speaking",
      "teamwork",
      "team environment",
      "work in a team",
      "collaboration",
      "collaborative",
      "works well with others",
    ],
    link: "/experience",
  },
  {
    id: "kb-languages-spoken",
    topic: "English fluency",
    text: "Yes — Siddartha is fully fluent in English: he works as an engineer at Amazon in Seattle, completed his Master's degree in the United States (NJIT), and regularly presents, mentors, and runs customer demos in English. It is his primary professional language.",
    keywords: [
      "english",
      "speak english",
      "english fluency",
      "fluent",
      "fluency",
    ],
    link: "/experience",
  },
  {
    id: "kb-certifications",
    topic: "Certifications",
    text: "Siddartha holds four industry certifications: AWS Certified Solutions Architect – Associate, AWS Certified Developer – Associate (issued Aug 2024), CompTIA Security+, and Certified Ethical Hacker (CEH) v12 from EC-Council. Together they span cloud architecture, application development, and offensive/defensive security — pairing naturally with his MS in Cyber Security & Privacy.",
    keywords: [
      "certifications",
      "aws certified",
      "solutions architect",
      "developer associate",
      "aws certs",
      "security+",
      "comptia",
      "ceh",
      "ethical hacker",
      "ec-council",
      "security certifications",
      "credentials",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-languages",
    topic: "Languages and frameworks",
    text: "Siddartha works with Java (Spring Boot), Python, and JavaScript/TypeScript (React, Node.js), plus deep learning frameworks PyTorch and TensorFlow. This spans backend services, front-end web development, and model training.",
    keywords: [
      "skills",
      "languages",
      "java",
      "spring boot",
      "python",
      "javascript",
      "typescript",
      "react",
      "node.js",
      "pytorch",
      "tensorflow",
      "frameworks",
      "programming languages",
      "programming",
      "coding",
      "code",
      "frontend",
      "backend",
      "full stack",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-cloud-mlops",
    topic: "Cloud and MLOps skills",
    text: "Siddartha's cloud and MLOps toolkit includes AWS, MLOps pipelines, CI/CD, Docker, Kubernetes, Terraform, and Amazon Bedrock, covering everything from infrastructure provisioning to automated model deployment.",
    keywords: [
      "skills",
      "cloud",
      "mlops",
      "aws",
      "docker",
      "kubernetes",
      "terraform",
      "ci/cd",
      "amazon bedrock",
      "devops",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-competencies",
    topic: "Core competencies",
    text: "Siddartha's core competencies include performance optimization, model deployment and monitoring, RAG systems, responsible AI, and distributed systems — the skill set behind his enterprise-scale ingestion and MLOps work.",
    keywords: [
      "skills",
      "core competencies",
      "performance optimization",
      "model monitoring",
      "rag systems",
      "responsible ai",
      "distributed systems",
    ],
    link: "/experience",
  },
  {
    id: "kb-artifact-timeline",
    topic: "The Climate of Machine Intelligence artifact",
    text: "The Climate of Machine Intelligence is an interactive web timeline Siddartha built, covering AI history from 1943 to 2025 through a weather metaphor of booms, winters, and thaws. It presents 40 curated milestones across six eras, filterable by category, with a clickable era barometer and a log-scale training-compute chart arguing that AI winters were driven by hardware and funding constraints rather than failures of the underlying theory.",
    keywords: [
      "artifact",
      "timeline",
      "climate of machine intelligence",
      "ai history",
      "booms",
      "winters",
      "thaws",
      "milestones",
      "compute chart",
      "ai winter",
      "data visualization",
      "project",
    ],
    link: "/artifacts/ai-ml-timeline",
  },
  {
    id: "kb-artifact-triage-copilot",
    topic: "Triage Copilot artifact",
    text: "Triage Copilot is an on-call triage AI agent Siddartha built in the AI Lab to guide engineers through 3am production alerts. It is a single-purpose LLM agent grounded in on-call documentation he curated for the AWS services he operates — Redshift, Lambda, and CloudWatch — answering with what is likely happening, what to check first, and how to mitigate. You can try it live on its artifact page.",
    keywords: [
      "artifact",
      "triage copilot",
      "on-call",
      "incident response",
      "agent",
      "chatbot",
      "generative ai",
      "llm agent",
      "grounding",
      "runbooks",
      "aws runbooks",
      "redshift",
      "lambda",
      "cloudwatch",
      "ai lab",
      "project",
    ],
    link: "/artifacts/triage-copilot",
  },
  {
    id: "kb-project-drowsiness",
    topic: "Drowsiness Detection AI project",
    text: "Drowsiness Detection AI is a real-time convolutional neural network pipeline Siddartha built in PyTorch, achieving 95% accuracy in production. It includes automated model-reliability monitoring with edge-case drift detection to keep accuracy stable as conditions change.",
    keywords: [
      "project",
      "drowsiness detection",
      "cnn",
      "pytorch",
      "computer vision",
      "95% accuracy",
      "drift monitoring",
      "real-time",
      "model reliability",
    ],
    link: "/experience",
  },
  {
    id: "kb-mentoring",
    topic: "Mentoring engineers",
    text: "Siddartha mentors engineers on GenAI and DevOps practices, having guided 6 engineers through weekly knowledge-sharing sessions. This mentoring contributed to a 20% reduction in deployment errors across the teams he supported.",
    keywords: [
      "mentoring",
      "mentor",
      "mentored",
      "mentorship",
      "knowledge sharing",
      "genai training",
      "devops training",
      "deployment errors",
      "20%",
      "leadership",
      "lead",
      "team lead",
    ],
    link: "/experience",
  },
  {
    id: "kb-value-proposition",
    topic: "Value proposition",
    text: "Siddartha is a software engineer specializing in cloud architecture and AI/ML systems who helps organizations turn raw enterprise data into intelligent, production-grade products. He builds high-throughput ingestion pipelines processing 10k+ documents a day and GenAI-driven MLOps that cut release cycles by 35%, and he shares what he learns by mentoring engineers and publishing hands-on resources like the artifacts in this portfolio.",
    keywords: [
      "value proposition",
      "why hire",
      "why should we hire",
      "what does he do",
      "summary",
      "elevator pitch",
      "overview",
      "about siddartha",
      "who is siddartha",
      "tell me about yourself",
      "introduce yourself",
      "introduction",
      "yourself",
      "strengths",
      "greatest strength",
      "career",
      "career history",
      "job history",
      "employment history",
      "years of experience",
      "experience",
    ],
    link: "/",
  },
  {
    id: "kb-resume",
    topic: "Résumé",
    text: "The full picture of Siddartha's experience — roles, metrics, education, certifications, and skills — is laid out on the Experience page of this site. For a copy of his résumé or anything specific, reach out directly via the contact page and he'll respond quickly.",
    keywords: [
      "resume",
      "cv",
      "curriculum vitae",
      "download resume",
      "copy of resume",
      "send resume",
    ],
    link: "/experience",
  },
  {
    id: "kb-contact",
    topic: "Contact information",
    text: "Siddartha is based in Seattle, WA and can be reached by email at siddarthadarisi@gmail.com. He's also on LinkedIn and GitHub under SiddarthaDarisi, and he's open to conversations with recruiters, collaborators, and fellow builders about AI/ML, cloud infrastructure, and MLOps.",
    keywords: [
      "contact",
      "email",
      "linkedin",
      "linkedin profile",
      "github",
      "reach out",
      "hire",
      "hiring",
      "recruiter",
      "location",
      "located",
      "based",
      "seattle",
      "get in touch",
      "open to opportunities",
      "opportunities",
      "available",
      "availability",
      "interview",
      "schedule a call",
      "meeting",
      "connect",
    ],
    link: "/contact",
  },
  {
    id: "kb-portfolio-build",
    topic: "How this portfolio was built",
    text: "This portfolio is built with Next.js 16 and Tailwind CSS v4, statically exported and deployed on GitHub Pages, with a custom hand-built design system. The \"Ask Siddartha\" chatbot itself is a client-side RAG system running entirely in the browser, retrieving from this knowledge base with no external chatbot service required.",
    keywords: [
      "portfolio",
      "how was this built",
      "tech stack",
      "next.js",
      "tailwind",
      "static export",
      "github pages",
      "design system",
      "this chatbot",
      "how the chatbot works",
      "this site",
    ],
    link: "/",
  },
  {
    id: "kb-summary-current-focus",
    topic: "Overall focus and mission",
    text: "Siddartha's north star is reliable, responsible AI at enterprise scale. Across Amazon and People Tech Group, his work centers on ingestion pipelines, MLOps automation, and RAG infrastructure that make AI dependable and production-ready for large organizations.",
    keywords: [
      "focus",
      "mission",
      "north star",
      "responsible ai",
      "enterprise scale",
      "rag infrastructure",
      "mlops automation",
      "career summary",
    ],
    link: "/",
  },
];

export const askSuggestions: string[] = [
  "What does Siddartha do at Amazon?",
  "Tell me about the Triage Copilot artifact.",
  "What are Siddartha's AWS certifications?",
  "What impact has he had at People Tech Group?",
  "How can I get in touch with Siddartha?",
];
