export interface KBChunk {
  id: string;
  topic: string;
  text: string;
  keywords: string[];
  link?: string;
}

export const profileKB: KBChunk[] = [
  {
    id: "kb-amazon-role",
    topic: "Current role at Amazon",
    text: "Siddartha is a Software Development Engineer at Amazon in Seattle, on the AWS Quick RAG team, where he has worked since October 2024. He builds high-throughput ingestion pipelines for Amazon Quick Suite, Q Business, and Kendra that process 10,000+ documents a day and power RAG and LLM experiences over enterprise data.",
    keywords: [
      "job",
      "work",
      "amazon",
      "current role",
      "current job",
      "employer",
      "aws quick rag",
      "quick suite",
      "q business",
      "kendra",
      "sde",
      "software development engineer",
      "seattle",
      "rag",
    ],
    link: "/experience",
  },
  {
    id: "kb-amazon-impact",
    topic: "Amazon impact and engineering details",
    text: "At Amazon, Siddartha architected large-scale index re-ingestion workflows that eliminate manual operations and enable zero-downtime updates as ML models evolve. He worked with cross-functional product and science teams to standardize ingestion across 10+ enterprise document formats, and he streamlined index ingestion by integrating validation and safe rollout mechanisms into CI/CD workflows, delivering 60% faster deployments for ML teams.",
    keywords: [
      "amazon impact",
      "re-ingestion",
      "zero downtime",
      "ci/cd",
      "deployment",
      "60%",
      "enterprise formats",
      "validation",
      "safe rollout",
      "index",
      "ingestion pipeline",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-role",
    topic: "Cloud Engineer role at People Tech Group",
    text: "Before Amazon, Siddartha was a Cloud Engineer at People Tech Group in Seattle from April 2024 to October 2024. He led customer demos for a GenAI-driven MLOps solution that converts natural-language prompts into validated Infrastructure-as-Code deployments, cutting release timelines by 35%.",
    keywords: [
      "people tech group",
      "cloud engineer",
      "previous job",
      "genai",
      "mlops",
      "natural language",
      "infrastructure as code",
      "iac",
      "35%",
      "release timelines",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-hca",
    topic: "HCA Healthcare document pipeline",
    text: "At People Tech Group, Siddartha built an AWS-based consent-forms processing pipeline for HCA Healthcare that used AI/ML to extract data from handwritten forms. This reduced manual data entry by more than 80% and shortened turnaround from days to minutes.",
    keywords: [
      "hca healthcare",
      "healthcare",
      "handwritten forms",
      "consent forms",
      "document pipeline",
      "80%",
      "manual entry",
      "ocr",
      "extraction",
    ],
    link: "/experience",
  },
  {
    id: "kb-ptg-infra",
    topic: "Infrastructure optimization at People Tech Group",
    text: "Siddartha also implemented automated scaling policies derived from cloud-usage analysis at People Tech Group, cutting infrastructure costs by 15%. He designed traffic-splitting algorithms that reduced microservice latency by 40ms for real-time AI inference workloads.",
    keywords: [
      "scaling policies",
      "cost reduction",
      "15%",
      "traffic splitting",
      "latency",
      "40ms",
      "microservices",
      "infrastructure",
      "real-time inference",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-njit",
    topic: "MS in Cyber Security & Privacy at NJIT",
    text: "Siddartha holds a Master of Science in Cyber Security & Privacy from the New Jersey Institute of Technology (NJIT). This graduate degree complements his software engineering background with a strong foundation in security and privacy principles applied to cloud and AI systems.",
    keywords: [
      "education",
      "njit",
      "masters",
      "ms",
      "cyber security",
      "privacy",
      "degree",
      "new jersey institute of technology",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-klu",
    topic: "B.Tech at KL University",
    text: "Siddartha earned his Bachelor of Technology in Computer Science & Engineering from the Koneru Lakshmaiah Education Foundation (KL University), which laid the foundation for his career in software development and cloud engineering.",
    keywords: [
      "education",
      "kl university",
      "koneru lakshmaiah",
      "btech",
      "bachelor",
      "computer science",
      "undergraduate degree",
    ],
    link: "/experience",
  },
  {
    id: "kb-education-iwu",
    topic: "Ongoing graduate study at Indiana Wesleyan University",
    text: "Siddartha is currently deepening his AI/ML expertise through graduate studies in AI & Machine Learning at Indiana Wesleyan University (IWU), in progress alongside his full-time work at Amazon.",
    keywords: [
      "education",
      "iwu",
      "indiana wesleyan university",
      "ai/ml program",
      "graduate studies",
      "in progress",
      "machine learning degree",
    ],
    link: "/experience",
  },
  {
    id: "kb-certifications",
    topic: "AWS certifications",
    text: "Siddartha holds two AWS Associate-level certifications: AWS Certified Solutions Architect – Associate and AWS Certified Developer – Associate, reflecting his hands-on expertise across AWS cloud architecture and application development.",
    keywords: [
      "certifications",
      "aws certified",
      "solutions architect",
      "developer associate",
      "aws certs",
      "credentials",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-languages",
    topic: "Languages and frameworks",
    text: "Siddartha works with Java (Spring Boot), Python, and JavaScript/TypeScript (React, Node.js), plus deep learning frameworks PyTorch and TensorFlow. This spans backend services, front-end web development, and model training.",
    keywords: [
      "skills",
      "languages",
      "java",
      "spring boot",
      "python",
      "javascript",
      "typescript",
      "react",
      "node.js",
      "pytorch",
      "tensorflow",
      "frameworks",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-cloud-mlops",
    topic: "Cloud and MLOps skills",
    text: "Siddartha's cloud and MLOps toolkit includes AWS, MLOps pipelines, CI/CD, Docker, Kubernetes, Terraform, and Amazon Bedrock, covering everything from infrastructure provisioning to automated model deployment.",
    keywords: [
      "skills",
      "cloud",
      "mlops",
      "aws",
      "docker",
      "kubernetes",
      "terraform",
      "ci/cd",
      "amazon bedrock",
      "devops",
    ],
    link: "/experience",
  },
  {
    id: "kb-skills-competencies",
    topic: "Core competencies",
    text: "Siddartha's core competencies include performance optimization, model deployment and monitoring, RAG systems, responsible AI, and distributed systems — the skill set behind his enterprise-scale ingestion and MLOps work.",
    keywords: [
      "skills",
      "core competencies",
      "performance optimization",
      "model monitoring",
      "rag systems",
      "responsible ai",
      "distributed systems",
    ],
    link: "/experience",
  },
  {
    id: "kb-artifact-timeline",
    topic: "The Climate of Machine Intelligence artifact",
    text: "The Climate of Machine Intelligence is an interactive web timeline Siddartha built, covering AI history from 1943 to 2025 through a weather metaphor of booms, winters, and thaws. It presents 40 curated milestones across six eras, filterable by category, with a clickable era barometer and a log-scale training-compute chart arguing that AI winters were driven by hardware and funding constraints rather than failures of the underlying theory.",
    keywords: [
      "artifact",
      "timeline",
      "climate of machine intelligence",
      "ai history",
      "booms",
      "winters",
      "thaws",
      "milestones",
      "compute chart",
      "ai winter",
      "data visualization",
      "project",
    ],
    link: "/artifacts/ai-ml-timeline",
  },
  {
    id: "kb-artifact-triage-copilot",
    topic: "Triage Copilot artifact",
    text: "Triage Copilot is an on-call triage AI agent Siddartha built in the AI Lab to guide engineers through 3am production alerts. It is a single-purpose LLM agent grounded in on-call documentation he curated for the AWS services he operates — Redshift, Lambda, and CloudWatch — answering with what is likely happening, what to check first, and how to mitigate. You can try it live on its artifact page.",
    keywords: [
      "artifact",
      "triage copilot",
      "on-call",
      "incident response",
      "agent",
      "chatbot",
      "grounding",
      "runbooks",
      "aws runbooks",
      "redshift",
      "lambda",
      "cloudwatch",
      "ai lab",
      "project",
    ],
    link: "/artifacts/triage-copilot",
  },
  {
    id: "kb-project-drowsiness",
    topic: "Drowsiness Detection AI project",
    text: "Drowsiness Detection AI is a real-time convolutional neural network pipeline Siddartha built in PyTorch, achieving 95% accuracy in production. It includes automated model-reliability monitoring with edge-case drift detection to keep accuracy stable as conditions change.",
    keywords: [
      "project",
      "drowsiness detection",
      "cnn",
      "pytorch",
      "computer vision",
      "95% accuracy",
      "drift monitoring",
      "real-time",
      "model reliability",
    ],
    link: "/experience",
  },
  {
    id: "kb-mentoring",
    topic: "Mentoring engineers",
    text: "Siddartha mentors engineers on GenAI and DevOps practices, having guided 6 engineers through weekly knowledge-sharing sessions. This mentoring contributed to a 20% reduction in deployment errors across the teams he supported.",
    keywords: [
      "mentoring",
      "mentor",
      "mentorship",
      "knowledge sharing",
      "genai training",
      "devops training",
      "deployment errors",
      "20%",
      "leadership",
    ],
    link: "/experience",
  },
  {
    id: "kb-value-proposition",
    topic: "Value proposition",
    text: "Siddartha is a software engineer specializing in cloud architecture and AI/ML systems who helps organizations turn raw enterprise data into intelligent, production-grade products. He builds high-throughput ingestion pipelines processing 10k+ documents a day and GenAI-driven MLOps that cut release cycles by 35%, and he shares what he learns by mentoring engineers and publishing hands-on resources like the artifacts in this portfolio.",
    keywords: [
      "value proposition",
      "why hire",
      "what does he do",
      "summary",
      "elevator pitch",
      "overview",
      "about siddartha",
    ],
    link: "/",
  },
  {
    id: "kb-contact",
    topic: "Contact information",
    text: "Siddartha is based in Seattle, WA and can be reached by email at siddarthadarisi@gmail.com. He's also on LinkedIn and GitHub under SiddarthaDarisi, and he's open to conversations with recruiters, collaborators, and fellow builders about AI/ML, cloud infrastructure, and MLOps.",
    keywords: [
      "contact",
      "email",
      "linkedin",
      "github",
      "reach out",
      "hire",
      "recruiter",
      "location",
      "seattle",
      "get in touch",
    ],
    link: "/contact",
  },
  {
    id: "kb-portfolio-build",
    topic: "How this portfolio was built",
    text: "This portfolio is built with Next.js 16 and Tailwind CSS v4, statically exported and deployed on GitHub Pages, with a custom hand-built design system. The \"Ask Siddartha\" chatbot itself is a client-side RAG system running entirely in the browser, retrieving from this knowledge base with no external chatbot service required.",
    keywords: [
      "portfolio",
      "how was this built",
      "tech stack",
      "next.js",
      "tailwind",
      "static export",
      "github pages",
      "design system",
      "chatbot",
      "rag",
      "client-side",
      "this site",
    ],
    link: "/",
  },
  {
    id: "kb-summary-current-focus",
    topic: "Overall focus and mission",
    text: "Siddartha's north star is reliable, responsible AI at enterprise scale. Across Amazon and People Tech Group, his work centers on ingestion pipelines, MLOps automation, and RAG infrastructure that make AI dependable and production-ready for large organizations.",
    keywords: [
      "focus",
      "mission",
      "north star",
      "responsible ai",
      "enterprise scale",
      "rag infrastructure",
      "mlops automation",
      "career summary",
    ],
    link: "/",
  },
];

export const askSuggestions: string[] = [
  "What does Siddartha do at Amazon?",
  "Tell me about the Triage Copilot artifact.",
  "What are Siddartha's AWS certifications?",
  "What impact has he had at People Tech Group?",
  "How can I get in touch with Siddartha?",
];
